cookie:
  expiry_days: 30
  key: pun_generation
  name: pun_generation_authentication
credentials:
  usernames:
    admin:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: Admin
      password: $2b$12$meOm0iDHhi2kOsQIMJ2qieqFWB7zfIt4h17P6djYzCG7wfc7.xFLa
