paths:
  data: "../data/evaluation.jsonl"
  results: "../results/evaluation"
splits:
  admin:
    - 9
    - 10
    - 11
    - 12
  evaluator_4:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  evaluator_8:
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  evaluator_2:
    - 13
    - 1
    - 2
    - 3
    - 4
  evaluator_24:
    - 5
    - 6
    - 7
    - 8
    - 9
  evaluator_7:
    - 10
    - 11
    - 12
    - 13
    - 1
  evaluator_1:
    - 2
    - 3
    - 4
    - 5
    - 6
  evaluator_6:
    - 7
    - 8
    - 9
    - 10
    - 11
  evaluator_23:
    - 12
    - 13
    - 1
    - 2
    - 3
  evaluator_5:
    - 4
    - 5
    - 6
    - 7
    - 8
  evaluator_3:
    - 9
    - 10
    - 11
    - 12
    - 13
  evaluator_20:
    - 16
    - 17
    - 18
    - 19
  evaluator_9:
    - 20
    - 21
    - 22
    - 23
  evaluator_17:
    - 24
    - 26
    - 27
    - 28
  evaluator_18:
    - 29
    - 30
    - 16
    - 17
  evaluator_11:
    - 18
    - 19
    - 20
    - 21
  evaluator_14:
    - 22
    - 23
    - 24
    - 26
  evaluator_12:
    - 27
    - 28
    - 29
    - 30
  evaluator_13:
    - 16
    - 17
    - 18
    - 19
  evaluator_15:
    - 20
    - 21
    - 22
    - 23
  evaluator_19:
    - 24
    - 26
    - 27
    - 28
  evaluator_21:
    - 29
    - 30
    - 16
    - 17
  evaluator_10:
    - 18
    - 19
    - 20
    - 21
  evaluator_22:
    - 22
    - 23
    - 24
    - 26
  evaluator_16:
    - 27
    - 28
    - 29
    - 30
