paths:
  data: "../data/evaluation.jsonl"
  results: "../results/evaluation.jsonl"
  style: "config/style.css"
splits:
  admin:
    - 1
    - 2
    - 3
    - 4
  hugo:
    - 5
    - 6
    - 7
    - 8
