cookie:
  expiry_days: 30
  key: pun_generation
  name: pun_generation_authentication
credentials:
  usernames:
    admin:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: admin
      password: $2b$12$0LnflKE9OfIv6aAGjWYxwO534Q/afw.tOBG5MoPcdf1K07VKwHR7a
    evaluator_23:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_23
      password: $2b$12$rs52igKhzq.euNhABJqV/utUopdjfsNKkIN.0UhnKRBDLhJuw8Cb.
    evaluator_4:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_4
      password: $2b$12$iYZz98ttNyejxnZSq9j/0u/r6AxarqZa1uB/MnwBp88gWn/oh8THO
    evaluator_9:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_9
      password: $2b$12$eodYSA6v54.NCEJq6wuftus6Y9SHRr8PKkVZm6fcWGbOhDQKog/BW
    evaluator_22:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_22
      password: $2b$12$MUcB/6jrHdHo9hci9U79N.3M587pLPQN8DHDOS2KZuctH0jheVR.2
    evaluator_18:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_18
      password: $2b$12$Su9rcLGuktW8ddUvtzzZvuEycZA4msxo.zWEiMY8guzzGmulsMfLi
    evaluator_16:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_16
      password: $2b$12$4GY.cfqrpCtY966dXkaYl.Hk/6Ka3WPMNPdKgNtLCb7UpZReL9732
    evaluator_10:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_10
      password: $2b$12$afHYXh1B80C8cjfhjwvqx.qJob6NlG2x2a3T760yTyFmIw5Gz0hrK
    evaluator_11:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_11
      password: $2b$12$IX1W9C1LqxC0Vog05p7aDuE5ep7ovm3sUXCtxbhLWrHkI.9nmfNRW
    evaluator_24:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_24
      password: $2b$12$dbRE2S3icI.G09y7BVhE6O.i/lQwBYpHcPHr3v9khRjMGpZ5hX.QS
    evaluator_2:
      email: null
      failed_login_attempts: 0
      logged_in: false
      name: evaluator_2
      password: $2b$12$pB4n0yqI0Ip6p5FV0QEz1.CGYCS.eBVxwEgawc.Tzly2j6tbYC6iO
    evaluator_7:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_7
      password: $2b$12$OSN/7UWgrc87j6ndGee8/.m0vEFyWKOExHV5XFzU/yw0xL.6p4yFK
    evaluator_12:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_12
      password: $2b$12$aG9WDOfGbJnYoP5VJdp8Ju51ZWw5GZJHHkAtVGlyGdJUTIwcB1g/a
    evaluator_20:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_20
      password: $2b$12$o26lOeYWwI.RUsytI0kWK.kibJMef07SEnuTszIcRbIdmaxFFi952
    evaluator_19:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_19
      password: $2b$12$PNwxJ79HFbMLCqDMiJGjzeysm.eEIEdE9e9u7/O4JrIR2I34jTeI.
    evaluator_8:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_8
      password: $2b$12$sdws3J/UD96T6lXyOoLW..I.qplRkPThqBENg2iXi/vHfjvBBZ56a
    evaluator_6:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_6
      password: $2b$12$r22/2Lc0oKQvO1iNPpdlCeXq9Ac9WXGEVFtMBxebUboSEzX7UeMvm
    evaluator_1:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_1
      password: $2b$12$ikfKDcXYsWEd13GncH3uAuF3yMBeHoHTcxelqv1TVHMom/uQGhP0m
    evaluator_15:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_15
      password: $2b$12$zp/zqBRAXlVMxprLR6XZieOqFoV1TuNJD26xN2QFY7XSI6ueP0FuS
    evaluator_14:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_14
      password: $2b$12$JESPwNsKflAdjhPTKwhUNuDlT3B81wAG7fjLhYDPZbgR9BgU5m3kC
    evaluator_13:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_13
      password: $2b$12$UzwZG/JLQvbogN8MjSZ/1.EoV0fRwwPUXtsbr4wBe0IFV/1Aw41Fe
    evaluator_21:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_21
      password: $2b$12$XosIKs2Sf3A2outfTp6sYOWay31921tEAAVCuv3fA9F8M1BR.sXfi
    evaluator_17:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_17
      password: $2b$12$2JDLVUmbT3vn1TI6hmOlperrg1S5vDjlgjQv9z4XuRxProftO4.Ra
    evaluator_3:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_3
      password: $2b$12$c6yrhfurZLKuPRsK72BW3uf6YKosM8VBXFNeq0mSizoVJISrf1Wu.
    evaluator_5:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: evaluator_5
      password: $2b$12$waIqjmAZV5ZZCHpId/CA2eELqR.1JyfYNDZaKL5Ye4r.BWsdyoD7q
