cookie:
  expiry_days: 30
  key: pun_generation
  name: pun_generation_authentication
credentials:
  usernames:
    admin:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: Admin
      password: $2b$12$0LnflKE9OfIv6aAGjWYxwO534Q/afw.tOBG5MoPcdf1K07VKwHR7a
    hugo:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: Hugo
      password: $2b$12$dbRE2S3icI.G09y7BVhE6O.i/lQwBYpHcPHr3v9khRjMGpZ5hX.QS
